title: About Vidit Madan
author: Vidit Madan 
email: vmadan2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 I like to play basketball
 I worked at Eagles Landing Day Camp Last Summer
 I attended a National Student Leadership Conference at American University

# social links
instagram_username: vidit572 # DO NOT include the @ character, or else the build will fail!
github_username:  vmadan2407 # DO NOT include the @ character, or else the build will fail!
linkedin_username: viditmadan3
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
